name: Build and Validate Configuration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]  # Run on Java 17 and more

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'  # Alternative: 'zulu', 'corretto', etc.
          cache: 'maven'  # Speeds up builds by caching dependencies

      - name: Build and Test
        run: mvn --batch-mode --update-snapshots clean package -DskipTests